<a href="https://colab.research.google.com/github/ramcharanpavanteja/FML/blob/main/logistic_regression_on_Heart.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

In [5]:
data = pd.read_csv("/content/drive/MyDrive/Heart.csv")

In [6]:
data

Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
0             1   63    1       typical     145   233    1        2    150   
1             2   67    1  asymptomatic     160   286    0        2    108   
2             3   67    1  asymptomatic     120   229    0        2    129   
3             4   37    1    nonanginal     130   250    0        0    187   
4             5   41    0    nontypical     130   204    0        2    172   
..          ...  ...  ...           ...     ...   ...  ...      ...    ...   
298         299   45    1       typical     110   264    0        0    132   
299         300   68    1  asymptomatic     144   193    1        0    141   
300         301   57    1  asymptomatic     130   131    0        0    115   
301         302   57    0    nontypical     130   236    0        2    174   
302         303   38    1    nonanginal     138   175    0        0    173   

     ExAng  Oldpeak  Slope   Ca        Thal  AHD  
0        0      2.3      3  0.0       fixed   No  
1        1      1.5      2  3.0      normal  Yes  
2        1      2.6      2  2.0  reversable  Yes  
3        0      3.5      3  0.0      normal   No  
4        0      1.4      1  0.0      normal   No  
..     ...      ...    ...  ...         ...  ...  
298      0      1.2      2  0.0  reversable  Yes  
299      0      3.4      2  2.0  reversable  Yes  
300      1      1.2      2  1.0  reversable  Yes  
301      0      0.0      2  1.0      normal  Yes  
302      0      0.0      1  NaN      normal   No  

[303 rows x 15 columns]

In [8]:
data = data.drop(columns = 'Unnamed: 0')

In [9]:
data

Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  \
0     63    1       typical     145   233    1        2    150      0   
1     67    1  asymptomatic     160   286    0        2    108      1   
2     67    1  asymptomatic     120   229    0        2    129      1   
3     37    1    nonanginal     130   250    0        0    187      0   
4     41    0    nontypical     130   204    0        2    172      0   
..   ...  ...           ...     ...   ...  ...      ...    ...    ...   
298   45    1       typical     110   264    0        0    132      0   
299   68    1  asymptomatic     144   193    1        0    141      0   
300   57    1  asymptomatic     130   131    0        0    115      1   
301   57    0    nontypical     130   236    0        2    174      0   
302   38    1    nonanginal     138   175    0        0    173      0   

     Oldpeak  Slope   Ca        Thal  AHD  
0        2.3      3  0.0       fixed   No  
1        1.5      2  3.0      normal  Yes  
2        2.6      2  2.0  reversable  Yes  
3        3.5      3  0.0      normal   No  
4        1.4      1  0.0      normal   No  
..       ...    ...  ...         ...  ...  
298      1.2      2  0.0  reversable  Yes  
299      3.4      2  2.0  reversable  Yes  
300      1.2      2  1.0  reversable  Yes  
301      0.0      2  1.0      normal  Yes  
302      0.0      1  NaN      normal   No  

[303 rows x 14 columns]

In [14]:
data['ChestPain'] = data['ChestPain'].astype('category')
data['ChestPain'] = data['ChestPain'].cat.codes
data

Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
0     63    1          3     145   233    1        2    150      0      2.3   
1     67    1          0     160   286    0        2    108      1      1.5   
2     67    1          0     120   229    0        2    129      1      2.6   
3     37    1          1     130   250    0        0    187      0      3.5   
4     41    0          2     130   204    0        2    172      0      1.4   
..   ...  ...        ...     ...   ...  ...      ...    ...    ...      ...   
298   45    1          3     110   264    0        0    132      0      1.2   
299   68    1          0     144   193    1        0    141      0      3.4   
300   57    1          0     130   131    0        0    115      1      1.2   
301   57    0          2     130   236    0        2    174      0      0.0   
302   38    1          1     138   175    0        0    173      0      0.0   

     Slope   Ca        Thal  AHD  
0        3  0.0       fixed   No  
1        2  3.0      normal  Yes  
2        2  2.0  reversable  Yes  
3        3  0.0      normal   No  
4        1  0.0      normal   No  
..     ...  ...         ...  ...  
298      2  0.0  reversable  Yes  
299      2  2.0  reversable  Yes  
300      2  1.0  reversable  Yes  
301      2  1.0      normal  Yes  
302      1  NaN      normal   No  

[303 rows x 14 columns]

In [16]:
data['Thal'] = data['Thal'].astype('category')
data['Thal'] = data['Thal'].cat.codes
data['AHD'] = data['AHD'].astype('category')
data['AHD'] = data['AHD'].cat.codes
data

Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
0     63    1          3     145   233    1        2    150      0      2.3   
1     67    1          0     160   286    0        2    108      1      1.5   
2     67    1          0     120   229    0        2    129      1      2.6   
3     37    1          1     130   250    0        0    187      0      3.5   
4     41    0          2     130   204    0        2    172      0      1.4   
..   ...  ...        ...     ...   ...  ...      ...    ...    ...      ...   
298   45    1          3     110   264    0        0    132      0      1.2   
299   68    1          0     144   193    1        0    141      0      3.4   
300   57    1          0     130   131    0        0    115      1      1.2   
301   57    0          2     130   236    0        2    174      0      0.0   
302   38    1          1     138   175    0        0    173      0      0.0   

     Slope   Ca  Thal  AHD  
0        3  0.0     1    0  
1        2  3.0     2    1  
2        2  2.0     3    1  
3        3  0.0     2    0  
4        1  0.0     2    0  
..     ...  ...   ...  ...  
298      2  0.0     3    1  
299      2  2.0     3    1  
300      2  1.0     3    1  
301      2  1.0     2    1  
302      1  NaN     2    0  

[303 rows x 14 columns]

In [78]:
data.isnull().sum()

Age          0
Sex          0
ChestPain    0
RestBP       0
Chol         0
Fbs          0
RestECG      0
MaxHR        0
ExAng        0
Oldpeak      0
Slope        0
Ca           4
Thal         0
AHD          0
dtype: int64

In [80]:
data=data.dropna()
data

Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
0     63    1          3     145   233    1        2    150      0      2.3   
1     67    1          0     160   286    0        2    108      1      1.5   
2     67    1          0     120   229    0        2    129      1      2.6   
3     37    1          1     130   250    0        0    187      0      3.5   
4     41    0          2     130   204    0        2    172      0      1.4   
..   ...  ...        ...     ...   ...  ...      ...    ...    ...      ...   
297   57    0          0     140   241    0        0    123      1      0.2   
298   45    1          3     110   264    0        0    132      0      1.2   
299   68    1          0     144   193    1        0    141      0      3.4   
300   57    1          0     130   131    0        0    115      1      1.2   
301   57    0          2     130   236    0        2    174      0      0.0   

     Slope   Ca  Thal  AHD  
0        3  0.0     1    0  
1        2  3.0     2    1  
2        2  2.0     3    1  
3        3  0.0     2    0  
4        1  0.0     2    0  
..     ...  ...   ...  ...  
297      2  0.0     3    1  
298      2  0.0     3    1  
299      2  2.0     3    1  
300      2  1.0     3    1  
301      2  1.0     2    1  

[299 rows x 14 columns]

In [81]:
X = data.drop(columns = 'AHD')
X

Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
0     63    1          3     145   233    1        2    150      0      2.3   
1     67    1          0     160   286    0        2    108      1      1.5   
2     67    1          0     120   229    0        2    129      1      2.6   
3     37    1          1     130   250    0        0    187      0      3.5   
4     41    0          2     130   204    0        2    172      0      1.4   
..   ...  ...        ...     ...   ...  ...      ...    ...    ...      ...   
297   57    0          0     140   241    0        0    123      1      0.2   
298   45    1          3     110   264    0        0    132      0      1.2   
299   68    1          0     144   193    1        0    141      0      3.4   
300   57    1          0     130   131    0        0    115      1      1.2   
301   57    0          2     130   236    0        2    174      0      0.0   

     Slope   Ca  Thal  
0        3  0.0     1  
1        2  3.0     2  
2        2  2.0     3  
3        3  0.0     2  
4        1  0.0     2  
..     ...  ...   ...  
297      2  0.0     3  
298      2  0.0     3  
299      2  2.0     3  
300      2  1.0     3  
301      2  1.0     2  

[299 rows x 13 columns]

In [82]:
y = data['AHD']
y

0      0
1      1
2      1
3      0
4      0
      ..
297    1
298    1
299    1
300    1
301    1
Name: AHD, Length: 299, dtype: int8

In [83]:
from sklearn.model_selection import train_test_split

In [84]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=21)

In [85]:
X_train

Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
290   67    1          1     152   212    0        2    150      0      0.8   
264   61    1          0     138   166    0        2    125      1      3.6   
197   45    0          0     138   236    0        2    152      1      0.2   
77    51    0          1     140   308    0        2    142      0      1.5   
15    57    1          1     150   168    0        0    174      0      1.6   
..   ...  ...        ...     ...   ...  ...      ...    ...    ...      ...   
189   69    1          1     140   254    0        2    146      0      2.0   
120   48    1          0     130   256    1        2    150      1      0.0   
48    65    0          1     140   417    1        2    157      0      0.8   
262   60    0          3     150   240    0        0    171      0      0.9   
209   62    0          0     150   244    0        0    154      1      1.4   

     Slope   Ca  Thal  
290      2  0.0     3  
264      2  1.0     2  
197      2  0.0     2  
77       1  1.0     2  
15       1  0.0     2  
..     ...  ...   ...  
189      2  3.0     3  
120      1  2.0     3  
48       1  1.0     2  
262      1  0.0     2  
209      2  0.0     2  

[209 rows x 13 columns]

In [86]:
X_test

Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
61    46    0          1     142   177    0        2    160      1      1.4   
300   57    1          0     130   131    0        0    115      1      1.2   
55    54    1          0     124   266    0        2    109      1      2.2   
245   67    1          0     120   237    0        0     71      0      1.0   
95    52    1          0     128   255    0        0    161      1      0.0   
..   ...  ...        ...     ...   ...  ...      ...    ...    ...      ...   
115   41    1          2     135   203    0        0    132      0      0.0   
117   35    0          0     138   183    0        0    182      0      1.4   
211   38    1          3     120   231    0        0    182      1      3.8   
233   74    0          2     120   269    0        2    121      1      0.2   
218   64    0          0     130   303    0        0    122      0      2.0   

     Slope   Ca  Thal  
61       3  0.0     2  
300      2  1.0     3  
55       2  1.0     3  
245      2  0.0     2  
95       1  1.0     3  
..     ...  ...   ...  
115      2  0.0     1  
117      1  0.0     2  
211      2  0.0     3  
233      1  1.0     2  
218      2  2.0     2  

[90 rows x 13 columns]

In [87]:
from sklearn.preprocessing import StandardScaler

In [88]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

In [89]:
X_test_scaled = scaler.fit_transform(X_test)

In [90]:
X_train_scaled

array([[ 1.38573367,  0.67185481,  0.21213203, ...,  0.70792084,
        -0.70203785,  1.13274336],
       [ 0.71454401,  0.67185481, -0.84347737, ...,  0.70792084,
         0.36119339, -0.49996949],
       [-1.07529507, -1.48841682, -0.84347737, ...,  0.70792084,
        -0.70203785, -0.49996949],
       ...,
       [ 1.16200378, -1.48841682,  0.21213203, ..., -1.01249144,
         0.36119339, -0.49996949],
       [ 0.60267907, -1.48841682,  2.32335085, ..., -1.01249144,
        -0.70203785, -0.49996949],
       [ 0.82640895, -1.48841682, -0.84347737, ...,  0.70792084,
        -0.70203785, -0.49996949]])

In [91]:
X_test_scaled

array([[-0.9102049 , -1.3462912 ,  0.06757374, ...,  1.97949865,
        -0.75727937, -0.52692446],
       [ 0.29126557,  0.74278135, -0.94603233, ...,  0.531085  ,
         0.3245483 ,  1.10835835],
       [-0.0364082 ,  0.74278135, -0.94603233, ...,  0.531085  ,
         0.3245483 ,  1.10835835],
       ...,
       [-1.7840016 ,  0.74278135,  2.09478587, ...,  0.531085  ,
        -0.75727937,  1.10835835],
       [ 2.14808356, -1.3462912 ,  1.08117981, ..., -0.91732864,
         0.3245483 , -0.52692446],
       [ 1.05583768, -1.3462912 , -0.94603233, ...,  0.531085  ,
         1.40637597, -0.52692446]])

In [92]:
model = LogisticRegression(random_state = 0).fit(X_train_scaled,y_train)

In [93]:
model.predict(X_train_scaled)

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0], dtype=int8)

In [97]:
model.score(X_train_scaled,y_train)

0.8708133971291866

In [99]:
X_test = scaler.transform(X_test)
y_pred = model.predict(X_test)

In [100]:
model.score(X_test, y_test)

0.8555555555555555

In [101]:
confusion_matrix(y_test, y_pred)

array([[44,  2],
       [11, 33]])

In [102]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      0.96      0.87        46
           1       0.94      0.75      0.84        44

    accuracy                           0.86        90
   macro avg       0.87      0.85      0.85        90
weighted avg       0.87      0.86      0.85        90

