<a href="https://colab.research.google.com/github/ramcharanpavanteja/FML/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [ ]:
a=np.array([20,30])
print(a)
print(a[0]+a[1])

[ 3.6 20.  30. ]
23.6


In [ ]:
print(a.shape)

(3,)


In [ ]:
a[0]=40
print(a)

[40 20 30]


In [ ]:
b=a
print(b)

[40 20 30]


In [ ]:
a=np.array([[10,20,30],[20,50,90]]) #creating multidimensional array
print(a)

[[10 20 30]
 [20 50 90]]


In [ ]:
print(a[0,0])

10


In [ ]:
print(a[0,2],"\n",a[1,0])

30 
 20


In [ ]:
print(a.shape)

(2, 3)


In [ ]:
a=np.zeros((2,2)) #creates 2 * 2 matrix with zeros
print(a)

[[0. 0.]
 [0. 0.]]


In [ ]:
a=np.ones([2,3])
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
a=np.full([3,3],8)
print(a)

[[8 8 8]
 [8 8 8]
 [8 8 8]]


In [4]:
a=np.eye(3,2)
print(a)


[[1. 0.]
 [0. 1.]
 [0. 0.]]
